model: ensemble
save_path: models/ensemble/
weights:
  - models/model_a/efficientnet_best.pth
  - models/model_b/convnext_image.pth
  - models/model_c/convnext_bird.pth
weights_ratio:
  - 0.2
  - 0.6
  - 0.2
data:
   val: data/processed/val_a.csv
   audio_dir: data/processed/audio/
inference:
  input_path: data/processed/126247/126247_iNat1109254_seg0.wav